### ISSUE TITLE
[Panic][3.0.0]: Thread Panics at Loading Screen before Title.

### ISSUE THREAD

**Issue by ElaineLMN** [Raytwo/ARCropolis#222] opened 2022-03-04 01:19 UTC
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

13.2.1

### Atmosphere Version

1.2.6

### Smash Version

13.0.1

### ARCropolis Version

3.0.0

### Version channel

Stable

### SD card formatting

FAT32

### Can the panic be consistently reproduced?

Yes

### Context

Literally just booted the game, and before the title screen-- BAM! Panic.

### Screenshot

![2022030320174000-1AB131B6E6571375B79964211BB3F5AE](https://user-images.githubusercontent.com/93639756/156680660-eca6d737-33bb-4cbc-9c65-f74a5235d1d4.jpg)

**Comment by Raytwo** [comment] 2022-03-11 08:39
Hello, did you migrate from 2.1.1 or from 3.0.0-beta? Also could you please provide a copy of your modpack with only the mod(s) that lead to this crash?

**Comment by ElaineLMN** [comment] 2022-03-11 09:12
Migrated from 3.0.0-beta 2.6. It was another plugin, like another NRO file.
[libcloud_seph_victory.zip](https://github.com/Raytwo/ARCropolis/files/8230591/libcloud_seph_victory.zip)

In any case, I switched back to 2.6 since I was having the same troubles with the mod manager as #219, and 2.6 was the last build that worked consistently for me. Had so many mods the menus chugged. Either way, I hope you can find out what's causing it!

**Comment by Raytwo** [comment] 2022-03-12 14:21
Thanks for the modpack, I'll look into it ASAP.
As for the menu lag, I'm sadly aware, there have been great improvements on that front already for 3.1.0 but there's still some noticeable lag I'd like to mitigate as much as possible before distributing it.

**Comment by Raytwo** [comment] 2022-03-12 16:22
Is this plugin using smashline or acmd-hook? Considering this is a plugin, ARCropolis shouldn't be causing any issue with it, but if the plugin is the cause, I'd need the source code to investigate.
Is this from some Gamebanana mod? I'd like the link if so.

**Comment by dfox20** [comment] 2022-03-12 16:36
> Thanks for the modpack, I'll look into it ASAP. As for the menu lag, I'm sadly aware, there have been great improvements on that front already for 3.1.0 but there's still some noticeable lag I'd like to mitigate as much as possible before distributing it.
> 
> EDIT: Is this plugin using smashline or acmd-hook? Considering this is a plugin, ARCropolis shouldn't be causing any issue with it, but if the plugin is the cause, I'd need the source code to investigate. Is this from some Gamebanana mod? I'd like the link if so.

It's from this mod https://gamebanana.com/sounds/51503

**Comment by Raytwo** [comment] 2022-03-13 23:17
Sorry, forgot to come back here, I can indeed confirm that the issue happens for me too, and we have some sort of an idea on what's happening, I'll try to get this fixed by 3.1.0 but if not, it should come shortly after.

**Comment by Raytwo** [comment] 2022-03-17 11:55
Issue fixed for ARCropolis 3.1.0, coming out today if everything goes well. Thanks for the report!

**Closed by Raytwo** 2022-03-17 11:55 UTC
Labels: bug, panic
