### ISSUE TITLE
[Panic][3.0.0 Beta 3]: Using Arcropolis-API causes a panic.

### ISSUE THREAD

**Issue by WuBoytH** [Raytwo/ARCropolis#205] opened 2022-02-01 20:06 UTC
### Have you read the disclaimer before proceeding?

- [X] I have read the disclaimer.

### System Firmware Version

13.2.1

### Atmosphere Version

1.2.6

### Smash Version

13.0.1

### ARCropolis Version

3.0.0-beta.3

### Version channel

Beta

### SD card formatting

FAT32

### Can the panic be consistently reproduced?

Yes

### Context

Attempting to run my arcropolis-api callbacks to patch ui_chara_db.prc causes a panic. Could potentially extend to other functions of the arcropolis-api.

You don't ask for a mod to test with so I'll link it here:
https://drive.google.com/file/d/1kHBhXZgbu8iEuM2K65iqXL6L8g6_4Col/view?usp=sharing

### Screenshot

![Mod Testing Screenshot 2022-02-01 14-58-41](https://user-images.githubusercontent.com/26860994/152042727-058396e7-62ad-486e-83eb-0cec0678e389.png)

### Configuration

version = '3.0.0-beta.3'
debug = false
auto_update = false
beta_updates = false
no_web_menus = false
region = 'us_en'

[paths]
arc = 'rom:/arc'
umm = 'rom:/arcropolis/workspaces/The WuBoy Ultimate Modpack/umm/'
extra_paths = []

[logger]
logger_level = 'Info'
log_to_file = true

**Comment by TripleLJ** [comment] 2022-02-01 22:39
I have the same issue. Here is my file that's causing it: 
[fighter_param.zip](https://github.com/Raytwo/ARCropolis/files/7982372/fighter_param.zip)

**Comment by TripleLJ** [comment] 2022-02-01 22:41
Also, it doesn't affect my other prcx files. It's specifically that one. That one to the best of my knowledge worked in a previous version of ARCropolis.

**Comment by dfox20** [comment] 2022-02-05 02:17
I same to get the same error code except the cause is from ble.prc. I don't know what that is specifically but if I remove these plugins, the 25m stage one, the english cloud one where his victory he says something different with sephiroth and the press start to end result screen one. The only one that seems to work for me is the toggle axis plugin and arc of course. These were working on 2.6 but not on 3.0 and 3.1

**Comment by dfox20** [comment] 2022-02-21 18:46
> I get the same error code except the cause is from ble.prc. I don't know what that is specifically but if I remove these plugins, the 25m stage one, the english cloud one where his victory he says something different with sephiroth defeated and the press start to end result screen one. The only one that seems to work for me is the toggle axis plugin and arc of course. These were working on 2.6 but not on 3.0 and 3.1.

I can confirm 3.2 still has the same issue unfortunately but keep up the great work devs!

**Comment by Raytwo** [comment] 2022-03-17 11:56
WuBoy is already aware of this but the issue is fixed as of ARCropolis 3.1.0, coming out today if everything goes well. Thanks for your reports!

**Closed by Raytwo** 2022-03-17 11:56 UTC
Labels: bug, panic
