### ISSUE TITLE
[Crash] ARCropolis v0.9.6 is amazing

### ISSUE THREAD

**Issue by Yummy-Yoshi** [Raytwo/ARCropolis#63] opened 2021-04-01 16:38 UTC
## Crash report

System firmware version: 11.0.1
Atmosphère version: 0.18.1
Smash version: 11.0.1
ARCropolis version: 2.0.0-beta, 1.0.5, and 0.9.6
microSD card format: FAT32

Okay so I've been tearing my hair out for the past week trying to figure out why mods weren't working. At first, the game wouldn't start at all and crash before it loaded with The Software Was Closed Because An Error Occurred or something. I thought I must've downloaded a corrupted mod, or Quasar was somehow messing the mods up, so I wiped everything and added mods one by one to see what the problem was. 
But when I added release version 1.0.5, the game would actually open now, for the most part. Yet even when I had just one model in the game, they would either crash the game before starting a match, infinitely load the game before a match, or if the match actually started, the textures would be all black. 
After talking to MowJow from Quasar, I figured it was a problem with me moving the positions of skins in Quasar, so when I moved the skins back into the slots they were made for, the game actually opened, and a lot less characters crashed the game, but a lot still did, like Ryu mods such as Casual Ryu, Wallace and Goku, and some mods would be mostly invisible except for some random polygons, like Peter Griffin or Balloon Luigi, or Ranger Ryu.
So I started thinking to myself, "I had NONE of these issues back when I first stated modding late last year", so just to test something, because I had already tried everything twice, I added ARCropolis v0.9.6 to my SD card. And voila, **every thing works fine!** I'd say the game is 95% functional now. No crashes in startup, no crashes loading a match, no black textures, no invisible janky models, it's perfect.

So my question is, why on Earth does ARCropolis get worse the more it gets updated? I mean is there a reason for this? These ARCropolis updates sounds great and look like they add a bunch of improvements, but clearly they don't work at all for me. I mean the latest version(2.0.2 or whatever) can't even start the game for me, and the one before that, the real latest version (1.0.5) probably only had ten mods that actually loaded fine. If the problem is somehow on my end, please let me know what's going on because I don't want to miss out on the new features being added to ARCropolis, but for now it's definitely more trouble than its worth using the new versions, so until then I'm sticking to the version that actually works.

**Comment by Angstdiscord** [comment] 2021-04-01 16:46
Ok now do dittos

**Comment by ClaudevonRiegan** [comment] 2021-04-01 16:50
The title should be "ARCropolis v0.9.6 users are amazing"

**Comment by blu-dev** [comment] 2021-04-01 16:51
Version 1.0.0 of ARCropolis removed the **bug** that allowed for one-slot mods to function "correctly". Versions 1.0.0 and above do not support proper one-slots, as they are fucking gruesome to implement (I speak from experience).

If you had read the changelog for any of the versions, you would be made aware that the mods which you are claiming no longer work, or which cause crashes, were never intended to work and only functioned as a side effect of the unstable replacement code ARCropolis was using.

As we attempt to reimplement functionality for one-slots properly, we welcome you to stay on whatever version you feel comfortable with, but claiming that "ARCropolis gets worse" is ignorant at best. 

If you are interested in more complete details as to why things are no longer working, I invite you to read the changelog which is provided in nearly every update. Thanks!

**Comment by Raytwo** [comment] 2021-04-01 16:53
Wow ok uh... That was a lot to process so let me address this:

First, read the changelogs on updates. Like, really. Everything you're complaining about has been addressed in the changelog of versions you mentioned in your issue.

* You complain the game broke because you moved mods on slots they weren't intended for.  
That's an user mistake, not an ARCropolis issue. I can't magically make Smash accept files it shouldn't.
* Mods would be invisible.  
That's because the mods you used are "one-slot", which was a glitch I warned multiple times about and people abused until it was FIXED in ARCropolis 1.0.0.  Blame the mod makers, not ARCropolis.
* You confirmed the mods worked on 0.9.6
Had you read the changelogs of the versions between 0.9.6 and 1.0.5, you'd have seen the massive text explaining what's up. Also just in case, major version (``X.0.0``) bumps when versioning mean something breaks. Crazy, right? I know, I know.

So uh, clearly, not, it's not getting worse. You're using it wrong is the thing.  
I can definitely agree that this should be indicated better and not require you to join a Discord server to keep up with the changes and you might have noticed that I added quite a few things to help users such as:
* A [wiki](https://github.com/Raytwo/ARCropolis/wiki) that I was filling up right before reading this
* A brand new changelog window that you should've seen since you mention using ARCropolis 2.0.0-beta
* Issue templates that you actually used to write this massive wall of text and completely disregarded the template that was pre-filled for you (proof once again that with all the signs, you ignore things and do it your own way)
* The README.md I just rewrote to inform users of all of this

Again, I can definitely agree some things could be done better and have been working on improving them but on the other hand you just did everything as poorly as possible, didn't look into any information source that could explain your issues and now you lash back at me for it.

**Closed** 2021-04-01 17:06 UTC
Labels: bug, crash

**Comment by Yummy-Yoshi** [comment] 2021-04-01 17:13
Woah woah woah I should've worded some things better, I'm not complaining about ARCropolis or saying it sucks or anything, I'm saying whatever is in my build sucks and I'm complaining about that. Clearly ARCropolis isn't the problem, of course I'm using it wrong, but I just wanted to know why so many problems arose as I went up the release versions, and how exactly I'm using it wrong, so I could use it right. Suffice to say you guys answered that question. Hopefully that curbs the passive aggressive answers you gave me. Like of course I read the wall of text, and I didn't disregard the template, it's rude of you to assume that I'm just ignoring all these things, in actuality, I'm just stupid and don't know what any of that means.

**Comment by Raytwo** [comment] 2021-04-01 17:26
Mh yes yes, ok so:
* You open an issue, take a "crash report" template, remove 75% of the required fields (when there was a "Open a blank issue" link under the templates btw)
* Write a massive wall of text trying to make a point things are getting worse while pretty much acknowledging through the entire thing and your reply that you've been using it wrong and know you were. But you posted it anyway.
* Open an issue to promote an old buggy version while dissing the new ones as "getting worse" when the template you claim you have read clearly says not to open issues for versions lower than the Current major one (which is ``1.x.x`` btw)
* Say we're being rude to assume things when you had no hesitation opening an issue looking down on all the hard work that went into > ``1.0.0`` that is just more stable in every possible way.

I get where you're coming from and I understand that you perhaps did not mean to indirectly "complain" but there are such things as wording and approach.  
Had you simply opened a blank issue asking why it seems like you have less issues on 0.9.6 than 1.0.5, you'd have been given a non-passive aggressive reply.

**Comment by Yummy-Yoshi** [comment] 2021-04-01 17:34
Yeah, yeah, I know, totally deserved. Sorry for any trouble, again, I'm just stupid. 
(And I'll be honest I did not notice the 'Open a blank issue' link)
Feel free to delete this thread, I don't want to spread misinformation, and keep up the good work dude!

**Comment by Raytwo** [comment] 2021-04-01 18:50
I very much appreciate that this could be solved peacefully, at this thread will be in the Closed issues so it should be fine.
I'd still like to thank you for your input by expressing your confusion, I'll strive to make things clearer when possible.
Have a great day, and sorry if you felt like we were being rude to you.
