### ISSUE TITLE
Crash Report, Arc Ver. 2.0.0-beta 8 - Crash Report with more than 5 players and Pokemon Trainer

### ISSUE THREAD

**Issue by difpron** [Raytwo/ARCropolis#151] opened 2021-10-20 18:15 UTC
### Your setup
System firmware version: ``13.0.0``
Atmosphère version: ``1.1.1``
Smash version: ``13.0``
ARCropolis version: ``2.0.0-beta``
microSD card format: ``FAT32`` 

### Reproducibility 
This can happen any amount of time when there are 5 plus players with a Pokemon Trainer in the match. As soon as the Versus screen appears the game freezes then crashes stating "Software closed to unknown error" I have the crash logs to exactly what happens. I also tested this with other modded users and they have stated this is something that also happens.

### What happened and what's the context?
This happens in World Of Light and Offline matches with 5 players or more with Pokemon Trainer in the match. 

### Configuration
[arcropolis.zip](https://github.com/Raytwo/ARCropolis/files/7383386/arcropolis.zip)

### Crash report

[01634747659_01006a800016e000.log](https://github.com/Raytwo/ARCropolis/files/7383388/01634747659_01006a800016e000.log)

**Comment by Raytwo** [comment] 2021-10-21 15:55
Duplicate of #102

**Closed as completed by Raytwo** 2021-10-21 15:55 UTC
Labels: bug, crash
