### ISSUE TITLE
[Feature suggestion] Simple config file for loading multiple mods/plugins

### ISSUE THREAD

**Issue by oasis-sharp** [Raytwo/ARCropolis#79] opened 2021-04-21 20:17 UTC
## Feature suggestion

A feature for the built in Arcadia feature (Possibly also for the standalone)

### What would the feature do?

While workspaces are an effective way to manage mods, they don't include plugins and require relocating files, sometimes duplicating them in the process, perhaps you could create a simple config file which could be loaded/edited that loads a set of plugins, and mods simultaneously, so gameplay mods could easily be switched between, without plugins being mixed up

### How should it be implemented?

Creating a config based off selected mods, and be able to load said saved configs from the Arcadia menu

### Additional information

For people making gameplay modpacks, they could include a config file *with* the modpack, so people can quickly load and unload all the needed mods without any confusion!

**Comment by Raytwo** [comment] 2021-06-12 12:54
That does sound like a pretty good idea, I've also had a discussion about being able to associate plugins with a modpack so that could be part of it.

**Comment by Raytwo** [comment] 2021-11-17 13:14
Duplicate of #135

**Closed by Raytwo** 2021-11-17 13:14 UTC
Labels: enhancement
