### ISSUE TITLE
[Crash] [ARCropolis 2.0.0 beta 5] Crashing after installing

### ISSUE THREAD

**Issue by Zenobia54** [Raytwo/ARCropolis#89] opened 2021-07-19 16:35 UTC
### Your setup
System firmware version: ``12.1.0``
Atmosphère version: ``0.19.5``
Smash version: ``12.0.0``
ARCropolis version: ``2.0.0-beta5``
microSD card format: ``FAT32`` 

### Reproducibility / Context
So I was super happy after the new beta came out, and I installed it instantly. I installed a bunch of mods I could not have before. When I was finally done, I tried booting the game, but it crashed instantly. 
I tried a lot of things: I confirmed that the game **did** launch when L loading the game and when disabling ARCropolis plugin.
With ARCropolis plugin active, the game **did not** launch even when disabling all my mods (I disabled them via ARCadia).

The configuration and the latest crash report are all below, my theory is that it doesn't like me being European, even after changing the arcropolis.toml file. 

### Configuration
(TOML files aren't supported by Git so here's everything) 

[infos]
version = "2.0.0"

[paths]
arc = "rom:/arc"
umm = "sd:/ultimate/mods"
extra_paths = []

[updater]
server_ip = "0.0.0.0"
beta_updates = false

[logger]
logger_level = "Info"

[misc]
debug = false
region = "eu_en"

### Crash report
[01626711827_01006a800016e000.log](https://github.com/Raytwo/ARCropolis/files/6842488/01626711827_01006a800016e000.log)

**Comment by blu-dev** [comment] 2021-07-19 21:06
Resolved, duplicate of [Issue 26](https://github.com/Raytwo/ARCropolis/issues/26)

No, it wasn't racist ;)

**Closed by blu-dev** 2021-07-19 21:06 UTC
Labels: bug, crash
